config/routes.rb
FishTagger::Application.routes.draw do
  # GEM FILE ROUTES
  apipie

  use_doorkeeper

  devise_for :users, :controllers => { registrations: :registrations }

  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # APPLICATION ROUTES

  scope '/admin' do
    resources :users do
      get :autocomplete_angler_angler_id, :on => :collection
      post :generate_new_password_email
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end

  end

  resources :angler_items do
    collection do
      post 'mark_fulfilled', action: :mark_fulfilled
    end
  end

  resources :about_tagging_programs

  resources :anglers do
    member do
      get 'data_count', action: :get_data_count
    end

    collection do
      get :autocomplete_angler_angler_id
      get 'search', action: :search
      get :download, defaults: { format: 'json' }

      scope :duplicates, as: :duplicates do
        get '/', action: :find_duplicates
        get :with_name, action: :duplicate_anglers
        get :with_ids, action: :duplicate_anglers
      end

      scope :merge, as: :merge do
        get '/', action: :merge_anglers
        get :canonical_angler, action: :canonical_angler
        post :perform, action: :perform_merge
      end

      post 'change_angler_id', action: :change_angler_id
      post 'transfer_data', action: :transfer_data
    end
  end

  resources :announcements

  controller :basin_sub_basin, as: 'basin_sub_basin',  path: 'basin_sub_basin' do
    get 'get_sub_basins', action: :get_sub_basins
    get 'basins', action: :basins
  end

  resources :blurbs

  resources :captures do
    collection do
      get :search
      get :import
      get :autocomplete_angler_angler_id
      get :autocomplete_tag_tag_no
      get :download, defaults: { format: 'json' }

      post :verify
      post :import, action: :import_commit
    end

    member do
      post :verify
      get :report
      get :partials
      get :convert_to_other
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :docs, as: :docs, path: 'docs' do
    get '/', to: redirect( '/docs/index.html' )
    get '*id', action: :show
  end

  resources :draft_captures do
    member do
      get 'status', action: :get_status
      get 'move_to_capture', action: :move_to_capture
      get :geo_json, defaults: { format: 'json' }
    end

    collection do
      get :download, defaults: { format: 'json' }
      post :move_to_captures
      delete :multi_delete
      post :refresh_errors
    end
  end
  
  controller :search do
      get 'get_search_data', :action => :get_search_data
  end

  resources :scratch_captures do
    member do
      post :convert_to_recapture, action: :convert_to_recapture
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :fish_entry_photos, as: :fish_entry_photos, path: :fish_entry_photos do
    get '/image/:id/:style/*filename', action: :image
    delete '/image/:id/:style/*filename', action: :destroy
  end

  resources :front_page_photo_stream_items

  resources :how_to_tags

  resources :news_items

  resources :notifications do
    collection do
      delete :destroy_all, action: :destroy_all
    end
  end

  resources :photos do
    member do
      get ':image_name', action: :show
    end
  end

  resources :recaptures do
    collection do
      get :download, defaults: { format: 'json' }
      post :verify
    end

    member do
      post :verify
      get :report
      get :partials
      get :convert_to_other
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :report, as: :report, path: 'reports' do
    get '/', action: :reports
    match :angler_info, via: [:get, :post]
    match :tagged_report, via: [:get, :post]
    match :days_at_large, via: [:get, :post]
    match :random_event, via: [:get, :post]
    match :data_check, via: [:get, :post]
    match :saltwater, via: [:get, :post]
    match :custom, via: [:get, :post]

    scope :sql, as: :sql do
      match :dump, action: :sql_dump, via: [:get, :post]
      match :csv, action: :sql_dump_csv, via: [:get, :post]
    end

    scope :angler, as: :angler do
      match :captures, action: :angler_captures, via: [:get, :post]
      match :recaptures, action: :angler_recaptures, via: [:get, :post]
      match :detail, action: :angler_events, via: [:get, :post]
      match :unused_kits, action: :angler_unused_kits, via: [:get, :post]
      match :banquet, action: :banquet_anglers, via: [:get, :post]
    end
  end

  controller :request_downloads, as: 'request_download', path: 'request_download' do
    get 'get', action: 'get'
    get 'file_is_ready', action: 'get_file_is_ready', defaults: { format: 'json' }
    post 'should_email', action: 'post_should_email', defaults: { format: 'json' }
  end

  controller :search, as: :search, path: :search do
    get '/', action: :index
  end

  resources :species do
    member do
      post :update_published
      post :update_target
    end

    collection do
      get '/image/:id/:image_name', action: :image
      post :sort
    end
  end

  resources :species_lengths
  
  scope '/stats', controller: :stats, as: :stats, defaults: { format: 'json' } do
    get '/', action: :index, defaults: { format: 'html' }
    get '/active_anglers', action: :active_anglers
    get '/total_anglers', action: :total_anglers
    get '/total_captures', action: :total_captures
    get '/total_recaptures', action: :total_recaptures
    get '/fish_event_points', action: :fish_event_points
    get '/fish_event_basins', action: :fish_event_basins
    get '/fish_event_heatmap', action: :fish_event_heatmap
    get '/species_counts', action: :species_counts
  end

  resources :tags, except: [:show, :new, :edit, :update, :create, :destroy] do
    get :autocomplete_angler_angler_id, :on => :collection
    get :autocomplete_tag_tag_no, :on => :collection

    collection do
      get :autocomplete_tag_number
      get :autocomplete_tag_number_any

      get '/search', action: :search
      get '/assign', action: :assign
      get '/unassign', action: :unassign
      get '/assigned', action: :assigned
      get '/deactivate', action: :deactivate

      post '/deactivate', action: :commit_deactivate
      post '/assign', action: :commit_assignment
      post '/unassign', action: :commit_unassignment
    end
  end

  resources :tag_lots do
    collection do
      get 'merge', action: :merge_tag_lots
    end
  end

  resources :user_tag_requests do
    member do
      post :update_fulfilled
    end
  end

  resources :volunteer_time_logs do
    member do
      get 'captures', action: :captures
    end
  end

  root to: 'welcome#index'
end

FishTagger::Application.routes.append do
  namespace :api, defaults: { format: 'json' } do

    # DEPRECATION on October 1, 2015
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]

      get '/me' => 'protected_api#me'

      # public api actions
      get '/combined_data' => 'public_api#get_combined_data'
      post '/combined_data' => 'public_api#get_combined_data'
      get '/species' => 'public_api#get_species'
      get '/species_lengths' => 'public_api#get_species_lengths'
      get '/about_tagging_program' => 'public_api#get_about_tagging_program'
      get '/how_to_tag' => 'public_api#get_how_to_tag'
      get '/time_of_day_options' => 'public_api#get_time_of_day_options'
      get '/fish_condition_options' => 'public_api#get_fish_condition_options'
      get '/recapture_disposition_options' => 'public_api#get_recapture_disposition_options'
      get '/shirt_size_options' => 'public_api#get_shirt_size_options'
      get '/blurbs' => 'public_api#get_blurbs'
      post '/add_unregistered_capture' => 'public_api#post_non_registered_capture'
      post '/create_unregistered_angler' => 'public_api#create_anon_cap_angler'
      get '/tag_history' => 'public_api#get_tag_history'
      get '/check_for_duplicate_captures' => 'public_api#check_for_duplicate_caps'
      get '/check_tag_exists' => 'public_api#check_tag_exists'
      get '/public_check_tag_exists' => 'public_api#public_check_tag_exists'
      get '/ajaxEmailAlreadyExists' => 'public_api#check_if_email_exists'
      post '/register' => 'public_api#create' #this is not behind authentication
      post '/reset_password' => 'public_api#reset_user_password'
      get '/capture_map_data' => 'public_api#capture_map_data'
      get '/news' => 'public_api#get_news_feed'
      get '/photo_stream' => 'public_api#get_photo_stream'
      get '/photos/:id/:image_name' => 'public_api#get_photos'
      get '/public_dashboard' => 'public_api#get_public_dashboard'
      get '/new_draft_capture' => 'public_api#get_new_draft_capture'
      get '/announcements' => 'public_api#get_announcements'

      # protected api actions
      get '/check_tag_exists_for_angler' => 'protected_api#check_tag_exists'
      get '/tags' => 'protected_api#get_tags'
      post '/tag_request' => 'protected_api#post_tag_request'
      get '/captures' => 'protected_api#get_captures'
      post '/captures' => 'protected_api#post_captures'
      post '/change_draft_capture_should_save' => 'protected_api#change_draft_capture_should_save'
      get '/draft_capture' => 'protected_api#get_draft_capture'
      get '/draft_captures' => 'protected_api#get_draft_captures'
      get '/draft_capture_status' => 'protected_api#get_status_for_draft'
      post '/draft_captures' => 'protected_api#post_draft_captures'
      post '/update_draft_capture' => 'protected_api#update_draft_capture'
      post '/volunteer_hours' => 'protected_api#post_volunteer_hours'
      get '/captures_dashboard' => 'protected_api#get_dashboard'

app/controllers/api/v2/protected/tags_controller.rb
module Api::V2::Protected
  class TagsController < ApiController
    include Api::V2::Protected::Concerns::QueryHelper
    include Api::V2::Protected::Concerns::InsertHelper

    resource_description do
      name 'Protected Tag API'
      short 'LDWF Protected Tag API'
      api_base_url "/api/v2/protected/tags"
      formats %w(json jsonp)
      error code: 401, desc: 'Authorization is required or user does not have the proper access role'
      error code: 422, desc: 'Missing or malformatted parameters'
      error code: 500, desc: 'Server had an unexpected issue processing your request'
      desc <<-EOS
        == Long description
        This API provides some public data to be used in front facing applications.
        Most of the data provided here is mainly relational lookup data.

        No authentication is required. All data at this endpoint is for public consumption.
      EOS
    end

    api :GET, '/'
    param :id, lambda { |val| Tag.where(id: val).any? }
    param :only_id_list, :bool, desc: 'Send the id list back to the client'
    param :updated_after, Time
    param :limit, :number
    param :offset, :number
    def index
      @items = query_tags(params, @user.angler_id)
    end

    api :GET, '/request'
    param :id, lambda { |val| UserTagRequest.where(id: val).any? }
    param :only_id_list, :bool, desc: 'Send the id list back to the client'
    param :updated_after, Time
    param :limit, :number
    param :offset, :number
    def get_requests
      @items = query_tag_requests(params, @user.angler_id)
    end

    api :POST, '/request'
    param :items, Array, required: true do
      param :tag_type, ['Redfish/Trout Tags', 'Inshore Tags'], required: true
      param :number_of_tags, :number, required: true
      param :uuid, Api::V2::ApiController::UUID_REGEX, required: true
    end
    def request
      #requests are only valid if the user is verified
      if @user.angler.try(:is_app_angler?) && !@user.verified
        render :json => { :errors => ['You are not yet verified please allow a few days for verification before requesting additional tags'],
                          :status => :unprocessable_entity } and return
      end
      data = insert_tag_requests(params, @user.angler_id)
      render json: data, status: data[:status]
    end
  end
end

app/helpers/tags_helper.rb
# == Schema Information
# Schema version: 20160405165101
#
# Table name: tags
#
#  id              :integer          not null, primary key
#  tag_no          :string(255)
#  tag_lot_id      :integer
#  tag_request_id  :integer
#  deleted         :boolean
#  unassign_option :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  old_anlger_id   :integer
#  prefix          :string(255)
#  active          :boolean          default(TRUE)
#  assigned_at     :datetime
#  recent          :boolean          default(TRUE), not null
#  search_vector   :tsvector         not null
#  angler_id       :integer
#
# Indexes
#
#  index_tags_on_angler_id      (angler_id)
#  index_tags_on_recent         (recent)
#  index_tags_on_search_vector  (search_vector)
#  index_tags_on_tag_lot_id     (tag_lot_id)
#  index_tags_on_tag_no         (tag_no) UNIQUE
#  tags_prefix_idx              (prefix)
#
# Foreign Keys
#
#  fk_rails_e4069f0b05  (angler_id => anglers.id)
#  tag_lot_fk           (tag_lot_id => tag_lots.id)
#

module TagsHelper
end

app/views/tags/assign.html.haml
%h1 Assign Tags

.table-container
  = form_tag(assign_tags_path, {role: 'form', id: 'assign_tag_form'}) do |form|
    = hidden_field_tag 'passed_angler_id', @angler_id
    .form-group
      = label_tag :angler_id
      = autocomplete_field_tag :angler_id, nil, autocomplete_angler_angler_id_anglers_path, data: { 'parsley-required' => true, 'auto-focus' => true, noMatchesLabel: 'No anglers found'  }, class: 'form-control uppercase-field'
    .form-group
      = label_tag :start_tag_number
      = text_field_tag :start_tag_number, nil, data: { 'parsley-required' => true,  'auto-focus' => true, noMatchesLabel: 'No assignable tags found' }, class: 'form-control uppercase-field'
    .form-group
      = label_tag :number_tags
      = text_field_tag :number_tags, nil, :class => 'form-control',  data: { 'parsley-min' => '1' }
    .form-group
      = label_tag :end_tag_number
      = text_field_tag :end_tag_number, nil, data: { 'parsley-required' => true,  'parsley-greaterthanequalfield' => '#start_tag_number', 'parsley-greaterthanequalfield-message' => 'Must be larger than or equal to the start tag number', 'auto-focus' => true, noMatchesLabel: 'No assignable tags found' }, class: 'form-control uppercase-field'
    = submit_tag 'Submit', class: 'btn btn-default'
    %button.btn.btn-danger{type: :reset} Clear

app/views/tags/assigned.haml
%h1 Tag assignments

.table-container
  = form_tag assigned_tags_path, {method: :post, class: 'month-filter'} do
    .row
      .col-md-3
        = label_tag 'Month filter'
    .row
      .col-md-2
        = select_month(Date.today, { prompt: 'Month' }, { class: 'month chosen-select' })
      .col-md-2
        = select_year(Date.today, {start_year: Date.today.year, end_year: 2012, prompt: 'Year'}, {class: 'year chosen-select'})
      .col-md-1
        = button_tag 'Reset', { class: 'btn btn-danger', type: :reset }

  %br/

  %table.table.table-striped
    %thead
      %tr
        %th Angler ID
        %th Angler Name
        %th Assignment Date
        %th Start Tag
        %th End Tag
        %th Number of Tags
        %th Last Tag Used
    %tbody

app/views/tags/deactivate.html.haml
%h1 Deactivate Tag

.table-container
  = form_tag(deactivate_tags_path, {role: 'form', id: 'deactivate_tag_form'}) do |form|
    .form-group
      = label_tag :tag_number
      = autocomplete_field_tag :tag_number, nil, autocomplete_tag_number_any_tags_path, data: { 'parsley-required' => true,  'auto-focus' => true, noMatchesLabel: 'No assignable tags found' }, class: 'form-control uppercase-field'
    = submit_tag 'Submit', class: 'btn btn-default'
    %button.btn.btn-danger{type: :reset} Clear

app/views/tags/index.html.erb
<h1>Tags</h1>

<div class="table-container">
<table id="tagsIndexList" class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>Angler ID</th>
      <th>Angler Name</th>
      <th>Entered</th>
      <th>Assigned</th>
      <th>Used</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>

app/views/tags/unassign.html.haml
%h1 Unassign Tags

.table-container
  = form_tag(unassign_tags_path, {role: 'form', id: 'assign_tag_form'}) do |form|
    .form-group
      = label_tag :start_tag_number
      = autocomplete_field_tag :start_tag_number, nil, autocomplete_tag_number_any_tags_path, data: { 'parsley-required' => true,  'auto-focus' => true, noMatchesLabel: 'No assignable tags found' }, class: 'form-control uppercase-field'
    .form-group
      = label_tag :number_tags
      = text_field_tag :number_tags, nil, :class => 'form-control', data: { 'parsley-min' => '1' }
    .form-group
      = label_tag :end_tag_number
      = autocomplete_field_tag :end_tag_number, nil, autocomplete_tag_number_any_tags_path, data: { 'parsley-required' => true,  'parsley-greaterthanequalfield' => '#start_tag_number', 'parsley-greaterthanequalfield-message' => 'Must be larger than or equal to the start tag number', 'auto-focus' => true, noMatchesLabel: 'No assignable tags found' }, class: 'form-control uppercase-field'
    = submit_tag 'Submit', class: 'btn btn-default'
    %button.btn.btn-danger{type: :reset} Clear