config/routes.rb
FishTagger::Application.routes.draw do
  # GEM FILE ROUTES
  apipie

  use_doorkeeper

  devise_for :users, :controllers => { registrations: :registrations }

  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # APPLICATION ROUTES

  scope '/admin' do
    resources :users do
      get :autocomplete_angler_angler_id, :on => :collection
      post :generate_new_password_email
    end

    resque_web_constraint = lambda do |request|
      current_user = request.env['warden'].user
      current_user.present? && current_user.has_role?(:admin)
    end

    constraints resque_web_constraint do
      mount ResqueWeb::Engine => "/resque_web"
      # mount RailsAdmin::Engine => '/rails'
    end

  end

  resources :angler_items do
    collection do
      post 'mark_fulfilled', action: :mark_fulfilled
    end
  end

  resources :about_tagging_programs

  resources :anglers do
    member do
      get 'data_count', action: :get_data_count
    end

    collection do
      get :autocomplete_angler_angler_id
      get 'search', action: :search
      get :download, defaults: { format: 'json' }

      scope :duplicates, as: :duplicates do
        get '/', action: :find_duplicates
        get :with_name, action: :duplicate_anglers
        get :with_ids, action: :duplicate_anglers
      end

      scope :merge, as: :merge do
        get '/', action: :merge_anglers
        get :canonical_angler, action: :canonical_angler
        post :perform, action: :perform_merge
      end

      post 'change_angler_id', action: :change_angler_id
      post 'transfer_data', action: :transfer_data
    end
  end

  resources :announcements

  controller :basin_sub_basin, as: 'basin_sub_basin',  path: 'basin_sub_basin' do
    get 'get_sub_basins', action: :get_sub_basins
    get 'basins', action: :basins
  end

  resources :blurbs

  resources :captures do
    collection do
      get :search
      get :import
      get :autocomplete_angler_angler_id
      get :autocomplete_tag_tag_no
      get :download, defaults: { format: 'json' }

      post :verify
      post :import, action: :import_commit
    end

    member do
      post :verify
      get :report
      get :partials
      get :convert_to_other
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :docs, as: :docs, path: 'docs' do
    get '/', to: redirect( '/docs/index.html' )
    get '*id', action: :show
  end

  resources :draft_captures do
    member do
      get 'status', action: :get_status
      get 'move_to_capture', action: :move_to_capture
      get :geo_json, defaults: { format: 'json' }
    end

    collection do
      get :download, defaults: { format: 'json' }
      post :move_to_captures
      delete :multi_delete
      post :refresh_errors
    end
  end
  
  controller :search do
      get 'get_search_data', :action => :get_search_data
  end

  resources :scratch_captures do
    member do
      post :convert_to_recapture, action: :convert_to_recapture
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :fish_entry_photos, as: :fish_entry_photos, path: :fish_entry_photos do
    get '/image/:id/:style/*filename', action: :image
    delete '/image/:id/:style/*filename', action: :destroy
  end

  resources :front_page_photo_stream_items

  resources :how_to_tags

  resources :news_items

  resources :notifications do
    collection do
      delete :destroy_all, action: :destroy_all
    end
  end

  resources :photos do
    member do
      get ':image_name', action: :show
    end
  end

  resources :recaptures do
    collection do
      get :download, defaults: { format: 'json' }
      post :verify
    end

    member do
      post :verify
      get :report
      get :partials
      get :convert_to_other
      get :geo_json, defaults: { format: 'json' }
    end
  end

  controller :report, as: :report, path: 'reports' do
    get '/', action: :reports
    match :angler_info, via: [:get, :post]
    match :tagged_report, via: [:get, :post]
    match :days_at_large, via: [:get, :post]
    match :random_event, via: [:get, :post]
    match :data_check, via: [:get, :post]
    match :saltwater, via: [:get, :post]
    match :custom, via: [:get, :post]

    scope :sql, as: :sql do
      match :dump, action: :sql_dump, via: [:get, :post]
      match :csv, action: :sql_dump_csv, via: [:get, :post]
    end

    scope :angler, as: :angler do
      match :captures, action: :angler_captures, via: [:get, :post]
      match :recaptures, action: :angler_recaptures, via: [:get, :post]
      match :detail, action: :angler_events, via: [:get, :post]
      match :unused_kits, action: :angler_unused_kits, via: [:get, :post]
      match :banquet, action: :banquet_anglers, via: [:get, :post]
    end
  end

  controller :request_downloads, as: 'request_download', path: 'request_download' do
    get 'get', action: 'get'
    get 'file_is_ready', action: 'get_file_is_ready', defaults: { format: 'json' }
    post 'should_email', action: 'post_should_email', defaults: { format: 'json' }
  end

  controller :search, as: :search, path: :search do
    get '/', action: :index
  end

  resources :species do
    member do
      post :update_published
      post :update_target
    end

    collection do
      get '/image/:id/:image_name', action: :image
      post :sort
    end
  end

  resources :species_lengths
  
  scope '/stats', controller: :stats, as: :stats, defaults: { format: 'json' } do
    get '/', action: :index, defaults: { format: 'html' }
    get '/active_anglers', action: :active_anglers
    get '/total_anglers', action: :total_anglers
    get '/total_captures', action: :total_captures
    get '/total_recaptures', action: :total_recaptures
    get '/fish_event_points', action: :fish_event_points
    get '/fish_event_basins', action: :fish_event_basins
    get '/fish_event_heatmap', action: :fish_event_heatmap
    get '/species_counts', action: :species_counts
  end

  resources :tags, except: [:show, :new, :edit, :update, :create, :destroy] do
    get :autocomplete_angler_angler_id, :on => :collection
    get :autocomplete_tag_tag_no, :on => :collection

    collection do
      get :autocomplete_tag_number
      get :autocomplete_tag_number_any

      get '/search', action: :search
      get '/assign', action: :assign
      get '/unassign', action: :unassign
      get '/assigned', action: :assigned
      get '/deactivate', action: :deactivate

      post '/deactivate', action: :commit_deactivate
      post '/assign', action: :commit_assignment
      post '/unassign', action: :commit_unassignment
    end
  end

  resources :tag_lots do
    collection do
      get 'merge', action: :merge_tag_lots
    end
  end

  resources :user_tag_requests do
    member do
      post :update_fulfilled
    end
  end

  resources :volunteer_time_logs do
    member do
      get 'captures', action: :captures
    end
  end

  root to: 'welcome#index'
end

FishTagger::Application.routes.append do
  namespace :api, defaults: { format: 'json' } do

    # DEPRECATION on October 1, 2015
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]

      get '/me' => 'protected_api#me'

      # public api actions
      get '/combined_data' => 'public_api#get_combined_data'
      post '/combined_data' => 'public_api#get_combined_data'
      get '/species' => 'public_api#get_species'
      get '/species_lengths' => 'public_api#get_species_lengths'
      get '/about_tagging_program' => 'public_api#get_about_tagging_program'
      get '/how_to_tag' => 'public_api#get_how_to_tag'
      get '/time_of_day_options' => 'public_api#get_time_of_day_options'
      get '/fish_condition_options' => 'public_api#get_fish_condition_options'
      get '/recapture_disposition_options' => 'public_api#get_recapture_disposition_options'
      get '/shirt_size_options' => 'public_api#get_shirt_size_options'
      get '/blurbs' => 'public_api#get_blurbs'
      post '/add_unregistered_capture' => 'public_api#post_non_registered_capture'
      post '/create_unregistered_angler' => 'public_api#create_anon_cap_angler'
      get '/tag_history' => 'public_api#get_tag_history'
      get '/check_for_duplicate_captures' => 'public_api#check_for_duplicate_caps'
      get '/check_tag_exists' => 'public_api#check_tag_exists'
      get '/public_check_tag_exists' => 'public_api#public_check_tag_exists'
      get '/ajaxEmailAlreadyExists' => 'public_api#check_if_email_exists'
      post '/register' => 'public_api#create' #this is not behind authentication
      post '/reset_password' => 'public_api#reset_user_password'
      get '/capture_map_data' => 'public_api#capture_map_data'
      get '/news' => 'public_api#get_news_feed'
      get '/photo_stream' => 'public_api#get_photo_stream'
      get '/photos/:id/:image_name' => 'public_api#get_photos'
      get '/public_dashboard' => 'public_api#get_public_dashboard'
      get '/new_draft_capture' => 'public_api#get_new_draft_capture'
      get '/announcements' => 'public_api#get_announcements'

      # protected api actions
      get '/check_tag_exists_for_angler' => 'protected_api#check_tag_exists'
      get '/tags' => 'protected_api#get_tags'
      post '/tag_request' => 'protected_api#post_tag_request'
      get '/captures' => 'protected_api#get_captures'
      post '/captures' => 'protected_api#post_captures'
      post '/change_draft_capture_should_save' => 'protected_api#change_draft_capture_should_save'
      get '/draft_capture' => 'protected_api#get_draft_capture'
      get '/draft_captures' => 'protected_api#get_draft_captures'
      get '/draft_capture_status' => 'protected_api#get_status_for_draft'
      post '/draft_captures' => 'protected_api#post_draft_captures'
      post '/update_draft_capture' => 'protected_api#update_draft_capture'
      post '/volunteer_hours' => 'protected_api#post_volunteer_hours'
      get '/captures_dashboard' => 'protected_api#get_dashboard'

app/controllers/report_controller.rb
class ReportController < ApplicationController

  before_action do
   authorize! :report, :reports
 end

  include ReportDataHelper
  include GetCapturesModule
  include ReportModule
  include DownloadableActionable

  before_action :prune_params
  before_filter :get_section
  skip_before_filter :verify_authenticity_token

  REPORT_SECTIONS = {
      :angler_info => 'angler_info',
      :tagged_fish => 'tagged_fish',
      :recaptured_fish => 'recaptured_fish',
      :unused_kits => 'unused_kits',
      :days_at_large => 'days_at_large',
      :captures_by_angler => 'captures_by_angler',
      :recaptures_by_angler => 'recaptures_by_angler',
      :captures_lottery => 'captures_lottery',
      :data_check => 'data_check',
      :saltwater_series => 'saltwater_series',
      :custom_capture_query => 'custom_capture_query',
      :banquet_anglers => 'banquet_anglers',
      :sql_dump => 'sql_dump'
  }

  def reports
  end

  def angler_info
    respond_to do |format|
      format.json {
        token = download_angler_info(params)
        render json: { token: token }
      }
    end
  end

  def tagged_report
    respond_to do |format|
      format.js {
        @items = get_tagged_fish_list(params)
        render 'get_report_section'
      }
      format.json {
        token = download_tagged_fish_list(params)
        render json: { token: token }
      }
    end
  end

  def angler_captures

    respond_to do |format|
      format.js {
        @items = get_captures_by_angler_list(params)
        render 'get_report_section'
      }
      format.json {
        token = download_captures_by_angler_list(params)
        render json: { token: token }
      }
    end
  end

  def angler_recaptures

    respond_to do |format|
      format.js {
        @items = get_recaptures_by_angler_list(params)
        render 'get_report_section'
      }
      format.json {
        token = download_recaptures_by_angler_list(params)
        render json: { token: token }
      }
    end
  end

  def angler_events
    # raise params.inspect
    clean_params = params.permit(:recaptures, :angler_id, :start_date, :end_date, :count, :start, :length, :draw, :order => [:column, :dir])
    requested_recaptures = (params[:recaptures] == 'true')

    respond_to do |format|
      format.json {
        json_data = get_events_detail_by_angler_list_helper(clean_params, requested_recaptures)
        render json: json_data
      }
    end
  end

  def angler_unused_kits
    # raise params.inspect
    clean_params = params.permit(:angler_id, :start_date, :end_date, :start, :length, :draw, :order => [:column, :dir])

    respond_to do |format|
      format.js {
        @items = get_unused_kits_list(clean_params)
        render 'get_report_section'
      }
      format.json {
        token = download_unused_kits_list(params)
        render json: { token: token }
      }
    end
  end

  def banquet_anglers
    # raise params.inspect
    clean_params = params.permit(:start_date, :end_date, :start, :length, :draw, :order => [:column, :dir])

    respond_to do |format|
      format.js {
        @items = get_banquet_list(clean_params)
        render 'get_report_section'
      }
      format.json {
        token = download_banquet_list(params)
        render json: { token: token }
      }
    end
  end


  def days_at_large

    respond_to do |format|
      format.js {
        @items = get_days_at_large_list(params)
        render 'get_report_section'
      }
      format.json {
        token = download_days_at_large_list(params)
        render json: { token: token }
      }
    end
  end

  def random_event
    respond_to do |format|
      format.js {
        @items = get_random_event_list(params)
        render 'get_report_section'
      }
    end
  end

  def data_check
    cleaned_params = params.permit(:start_date,:end_date,:user_id)
    respond_to do |format|
      format.js {
        @items = get_data_check_list(cleaned_params)
      }
      format.json {
        token = download_data_check_list(cleaned_params)
        render json: { token: token }
      }
    end
  end

  #Saltwater series data
  def saltwater
    p = params[:custom_query]

    p[:search] = {
        captures: true,
        recaptures: false
    }

    p[:config] = {
        recaptures: true
    }

    p[:terms][:anglers] = %w(LAW9909 LAW9912 LAW9915).map { |t| { angler_id: t }  }

    # create the file name
    min = p[:terms][:capture_date][:min].blank? ? 'First' : p[:terms][:capture_date][:min]
    max = p[:terms][:capture_date][:max].blank? ? 'Last' : p[:terms][:capture_date][:max]
    filename = "saltwater_series_for_#{min}_to_#{max}.xlsx"

    # create the token
    token = get_custom_query_token(p, filename)

    # respond with a JSON request
    respond_to do |format|
      format.json {
        # send the token that can be claimed later
        render json: { token: token }
      }
    end # end respond_to
  end


  def custom
    p = params[:custom_query]

    # cleanup the options from the chosen multi select
    p[:terms][:species]                = p[:terms][:species].reject { |t| t.values.first.blank? }
    p[:terms][:basin]                  = p[:terms][:basin].reject { |t| t.values.first.blank? }
    p[:terms][:sub_basin]              = p[:terms][:sub_basin].reject { |t| t.values.first.blank? }
    p[:terms][:species]                = p[:terms][:species].reject { |t| t.values.first.blank? }
    p[:terms][:time_of_day_options]    = p[:terms][:time_of_day_options].reject { |t| t.values.first.blank? }
    p[:terms][:fish_condition_options] = p[:terms][:fish_condition_options].reject { |t| t.values.first.blank? }

    # create the file name
    # TODO need to check the params coming in
    # p[:terms][:anglers] = p[:terms][:anglers].map { |a| { angler_id: Angler.from_ambiguous_id(a).try(:id) }  }
    min = p[:terms][:capture_date][:min].blank? ? 'First' : p[:terms][:capture_date][:min]
    max = p[:terms][:capture_date][:max].blank? ? 'Last' : p[:terms][:capture_date][:max]
    filename = "Captures_for_#{min}_to_#{max}.xlsx"

    # create the token
    token = get_custom_query_token(p, filename)

    # respond with a JSON request
    respond_to do |format|
      format.json {
        # send the token that can be claimed later
        render json: { token: token }
      }
    end # end respond_to

  end

  def sql_dump
    if current_user.has_role? :admin
      respond_to do |format|
        format.json {
          token = download_sql_dump(params)
          render json: { token: token }
        }
      end
    else

    end
  end

  def sql_dump_csv
    if current_user.has_role? :admin
      respond_to do |format|
        format.json {
          token = download_sql_dump(params.merge(csv: true))
          render json: { token: token }
        }
      end
    else

    end
  end

  private

  def prune_params
    params[:start_date]  = params[:start_date].gsub(/__\/__\/____/, '').presence if params[:start_date].present?
    params[:end_date]    = params[:end_date].gsub(/__\/__\/____/, '').presence   if params[:end_date].present?
    params[:angler_id]   = params[:angler_id].presence

    params
  end

  def get_section
    @section = ReportController::REPORT_SECTIONS[params[:section].try(:to_sym) || :angler_info]
  end


  def get_custom_query_token(params, filename)
    # create the token
    token = generate_download_token

    # create the download item with the token, the filename, and the if of the user that created it
    RequestedDownload.create!(token: token, filename: filename, user_id: current_user.id)

    # start the job to create the file
    CustomQueryJob.perform_later(params, token)

    token
  end

end

app/helpers/report_helper.rb
module ReportHelper

  def nav_link(name, section, active = false)
    link_to name, '#', class: "list-group-item#{' active' if active}", 'data-path' => report_path(section: section), 'data-section' => section
  end
end

app/views/report/reports/_angler_info.html.haml
-# we need to have to locals passed in, :path and :recapture
%section#report_container
  = form_tag report_angler_info_path, remote: true, onsubmit: 'downloadWaitingDialog.show("Loading")' do
    = hidden_field_tag :section, @section

    .row
      .col-md-3
        .form-group
          = label_tag :start_date, 'Start Date'
          = date_picker_field_tag :start_date, nil, class: 'form-control',  data: { 'parsley-beforetoday' => ''}
      .col-md-3
        .form-group
          = label_tag :end_date, 'End Date'
          = date_picker_field_tag :end_date, nil, class: 'form-control',  data: { 'parsley-beforetoday' => '', 'parsley-greaterthandatefield' => '#start_date', 'parsley-greaterthandatefield-message' => 'Must be after the start date' }
      .col-md-3
        .form-group
          = label_tag :minimum_captures, 'Minimum Captures'
          = text_field_tag :minimum_captures
    .row
      .col-md-1
        = button_tag 'Reset', class: 'btn btn-danger form-control', type: 'reset'
      .col-md-2
        %button.btn.btn-default.pull-right.download{type: 'button'}
          %i.fa.fa-download
          Download

app/views/report/reports/_captures_by_angler.html.haml
%section#report_container
  = render partial: 'report/reports/partials/event_by_angler', locals: { path: report_angler_captures_path }
  = render partial: 'report/modals/capture_detail'

app/views/report/reports/_custom_capture_query.html.haml
%section#report_container
  = form_tag report_custom_path, remote: true do

    .field-set
      .row
        .col-md-2
          %h5 Angler ID(s)
        .col-md-3
          .btn-group{role: :group}
            = button_tag font_awesome_icon('fa-plus').html_safe, class: 'btn btn-default add', type: :button
            = button_tag font_awesome_icon('fa-minus').html_safe, class: 'btn btn-default remove collapse', type: :button
      .row.multiple
        .col-md-12
          .input-group
            = autocomplete_field_tag 'custom_query[terms][anglers][][angler_id]' , nil, autocomplete_angler_angler_id_anglers_path, class: 'form-control'
            %span.input-group-addon.hidden AND

    .field-set
      .row
        .col-md-2
          %h5 Tag Number(s)
        .col-md-3
          .btn-group{role: :group}
            = button_tag font_awesome_icon('fa-plus').html_safe, class: 'btn btn-default add', type: :button
            = button_tag font_awesome_icon('fa-minus').html_safe, class: 'btn btn-default remove collapse', type: :button
            = button_tag 'Range', class: 'btn btn-default range', type: :button
      .row.numbers.multiple
        .col-md-12
          .input-group
            = autocomplete_field_tag 'custom_query[terms][tags][][tag_number]' , nil, autocomplete_tag_number_any_tags_path, class: 'form-control'
      .row.range.collapse
        .col-md-4
          .input-group
            = autocomplete_field_tag :tag_min, nil, autocomplete_tag_number_any_tags_path, name: 'custom_query[terms][tag_range][min]', class: 'form-control'
            %span.input-group-addon TO
            = autocomplete_field_tag :tag_max, nil, autocomplete_tag_number_any_tags_path, name: 'custom_query[terms][tag_range][max]', class: 'form-control', data: { 'parsley-greaterthanfield' => '#tag_min', 'parsley-greaterthandatefield-message' => 'Must be after the start tag' }

    .field-set
      .row
        .col-md-2
          %h5 Location Description
        .col-md-3
          .btn-group{role: :group}
            = button_tag font_awesome_icon('fa-plus').html_safe, class: 'btn btn-default add', type: :button
            = button_tag font_awesome_icon('fa-minus').html_safe, class: 'btn btn-default remove collapse', type: :button
      .row.multiple
        .col-md-12
          .input-group
            = text_field_tag :location , nil, class: 'form-control', name: 'custom_query[terms][location_descriptions][][location_term]'
            %span.input-group-addon.hidden AND

    .field-set
      .row
        .col-md-2
          %h5 Comments
        .col-md-3
          .btn-group{role: :group}
            = button_tag font_awesome_icon('fa-plus').html_safe, class: 'btn btn-default add', type: :button
            = button_tag font_awesome_icon('fa-minus').html_safe, class: 'btn btn-default remove collapse', type: :button
      .row.multiple
        .col-md-12
          .input-group
            = text_field_tag :comments , nil, class: 'form-control', name: 'custom_query[terms][comments][][comment_term]'
            %span.input-group-addon.hidden AND

    .field-set
      .row
        .col-md-2
          %h5 Length Range
      .row
        .col-md-4
          .input-group
            = text_field_tag :range_min , nil, class: 'form-control', name: 'custom_query[terms][length][min]', placeholder: 'Min'
            %span.input-group-addon TO
            = text_field_tag :range_max , nil, class: 'form-control', name: 'custom_query[terms][length][max]', placeholder: 'Max',  data: { 'parsley-greaterthandatefield' => '#range_min', 'parsley-greaterthandatefield-message' => 'Must be larger than the min length' }

    .field-set
      .row
        .col-md-2
          %h5 Date Range
      .row
        .col-md-4
          .input-group
            = date_picker_field_tag :date_min , nil, class: 'form-control', name: 'custom_query[terms][capture_date][min]', placeholder: 'Min'
            %span.input-group-addon TO
            = date_picker_field_tag :date_max , nil, class: 'form-control', name: 'custom_query[terms][capture_date][max]', placeholder: 'Max', data: { 'parsley-greaterthandatefield' => '#date_min', 'parsley-greaterthandatefield-message' => 'Must be after min date' }

    .field-set
      .row
        .col-md-2
          %h5 Time of Day
          %p.help-block To select "All", leave blank
      .row
        .col-md-12
          .input-group{style: 'width: 100%'}
            = collection_select :time_of_day_option, :time_of_day, TimeOfDayOption.all, :id, :time_of_day_option, {include_blank: false}, {multiple: true, name: 'custom_query[terms][time_of_day_options][][time_of_day]', class: 'form-control chosen-select'}

    .field-set
      .row
        .col-md-2
          %h5 Fish Condition
          %p.help-block To select "All", leave blank
      .row
        .col-md-12
          .input-group{style: 'width: 100%'}
            = collection_select :fish_condition_option, :fish_condition, FishConditionOption.all, :id, :fish_condition_option, {include_blank: false}, {multiple: true, name: 'custom_query[terms][fish_condition_options][][fish_condition]', class: 'form-control chosen-select'}

    .field-set
      .row
        .col-md-2
          %h5 Basins
          %p.help-block To select "All", leave blank
      .row
        .col-md-12
          .input-group{style: 'width: 100%'}
            - sub_basin_json = { data: Basin.includes(:sub_basins).to_a.each_with_object({}){ |basin,hash| hash[basin.gid.to_s] = basin.sub_basins.order(name: :asc).map{ |s| { gid: s.gid, basin_gid: s.basin.gid, name: "#{s.basin.name} - #{s.name}"}}}}.to_json.to_s
            = collection_select :basins, :basin, Basin.order('name asc').all, :gid, :name, {include_blank: false}, { multiple: true, name: 'custom_query[terms][basin][][basin_id]', class: 'form-control chosen-select', "data-sub-basin" => sub_basin_json }

    .field-set
      .row
        .col-md-4
          %h5 Sub Basins
          %p.help-block To select "All", leave blank
      .row
        .col-md-12
          .input-group{style: 'width: 100%'}
            = select(:sub_basins, :sub_basin, [], {include_blank: false}, {multiple: true, name: 'custom_query[terms][sub_basin][][sub_basin_id]', class: 'form-control chosen-select'})

    .field-set
      .row
        .col-md-3
          %h5 Species
          %p.help-block To select "All", leave blank
      .row
        .col-md-12
          .input-group{style: 'width: 100%'}
            = collection_select(:species, :species_id, Species.order('common_name asc').all, :id, :common_name, {include_blank: false}, {multiple: true, name: 'custom_query[terms][species][][species_id]', class: 'form-control chosen-select'})

    .field-set
      .row
        .col-md-3
          %h5 Search On
      .row
        .col-md-2
          .checkbox
            = label_tag :captures do
              = check_box_tag :captures, 1, true, name: 'custom_query[search][captures]', class: 'checkbox'
              Captures
        .col-md-2
          .checkbox
            = label_tag :recaptures do
              = check_box_tag :recaptures, 1, nil, name: 'custom_query[search][recaptures]', class: 'checkbox'
              Recaptures

    .field-set
      .row
        .col-md-3
          %h5 Include Columns From
      .row
        .col-md-2
          .checkbox
            = label_tag :captures do
              = check_box_tag :captures, 1, true, :name => 'custom_query[config][captures]', class: 'checkbox'
              Captures
        .col-md-2
          .checkbox
            = label_tag :recaptures do
              = check_box_tag :recaptures, 1, true, :name => 'custom_query[config][recaptures]', class: 'checkbox'
              Recaptures

    = button_tag 'Download', class: 'btn btn-default download', type: :button

app/views/report/reports/_days_at_large.html.haml
%section#report_container
  = form_tag report_days_at_large_path, remote: true do
    = hidden_field_tag :section, @section

    .row
      .col-md-3
        .form-group
          = label_tag :angler_id, 'Angler ID'
          = autocomplete_field_tag :angler_id, '', autocomplete_angler_angler_id_anglers_path, :class => 'form-control'
    .row
      .col-md-3
        .form-group
          = label_tag :time_frame, 'Max Days'
          = text_field_tag :time_frame, nil, placeholder: 'Defaults to 365', class: 'form-control', data: { 'parsley-min' => '1' }
      .col-md-3
        .form-group
          = label_tag :start_date, 'Start Date'
          = date_picker_field_tag :start_date, nil, class: 'form-control', data: { 'parsley-beforetoday' => '' }
      .col-md-3
        .form-group
          = label_tag :end_date, 'End Date'
          = date_picker_field_tag :end_date, nil, class: 'form-control', data: { 'parsley-beforetoday' => '', 'parsley-greaterthandatefield' => '#start_date', 'parsley-greaterthandatefield-message' => 'Must be after the start date' }
      .col-md-3
        .form-group
          = label_tag :species, 'Species'
          = select_tag :species_id, options_from_collection_for_select(Species.order('ordinal_position desc, common_name asc').all, :id, :common_name), {:include_blank => true, :class => 'form-control chosen-select'}

    .row
      .col-md-1
        = button_tag 'Reset', class: 'btn btn-danger form-control', type: 'reset'
      .col-md-1
        = submit_tag 'Submit', class: 'btn btn-default form-control'

    #results
      %hr
      %h3 Results
      %table.table.table-striped
        %thead
          %tr
            %th Angler ID
            %th First Name
            %th Last Name
            %th Tag Number
            %th Species
            %th Capture Date
            %th Recapture Date
            %th Days At Large
        %tbody

app/views/report/reports/_sql_dump.haml
%section#report_container
  = form_tag report_sql_dump_path, remote: true do
    = hidden_field_tag :section, @section

    .results
      %hr
        .row
      .col-md-5
        %h3 Download SQL Dump
      .col-md-5
        %button.btn.btn-default.download.pull-right{type: 'button'} Download

  = form_tag report_sql_csv_path, remote: true do
    = hidden_field_tag :section, @section

    .results
      %hr
        .row
      .col-md-5
        %h3 Download SQL Dump as CSV
      .col-md-5
        %button.btn.btn-default.download.pull-right{type: 'button'} Download